name: NoTell
main: awzaw\notell\Main
version: 1.0.0
api: [1.13.0, 1.14.0, 2.0.0]
load: POSTWORLD
author: awzaw
website: https://github.com/awzaw
commands:
 notell:
  description: "Refuse all Tell Messages"
  usage: "/notell"
  permission: notell
permissions:
  notell:
    description: "Allows Use of /notell"
    default: op